# Generated by Django 4.0.6 on 2022-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prismID', models.CharField(max_length=200)),
                ('workOrderId', models.CharField(max_length=200)),
                ('PO', models.CharField(max_length=200)),
                ('POAmount', models.CharField(blank=True, max_length=200)),
                ('ConstType', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
