# Generated by Django 4.0.6 on 2022-08-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_workorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workOrder',
        ),
    ]
