# Generated by Django 4.0.6 on 2022-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prismID', models.CharField(max_length=200)),
                ('workOrderId', models.CharField(max_length=200)),
                ('PO', models.CharField(max_length=200)),
                ('POAmount', models.CharField(blank=True, max_length=200)),
                ('ConstType', models.CharField(blank=True, max_length=200)),
                ('ConstCoordinator', models.CharField(blank=True, max_length=200)),
                ('WorkOrderDate', models.CharField(blank=True, max_length=200)),
                ('EstCompletion', models.CharField(blank=True, max_length=200)),
                ('IssuedBy', models.CharField(blank=True, max_length=200)),
                ('JobName', models.CharField(blank=True, max_length=200)),
                ('JobAddress', models.CharField(blank=True, max_length=200)),
                ('SiteContactName', models.CharField(blank=True, max_length=200)),
                ('SitePhoneNumber', models.CharField(blank=True, max_length=200)),
                ('Comments', models.CharField(blank=True, max_length=200)),
                ('Status', models.CharField(blank=True, max_length=200)),
                ('CloseDate', models.CharField(blank=True, max_length=200)),
                ('WCSup', models.CharField(blank=True, max_length=200)),
                ('UploadDate', models.CharField(blank=True, max_length=200)),
                ('UserName', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
