# Generated by Django 4.0.6 on 2022-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='CloseDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='ConstCoordinator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='ConstType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='EstCompletion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='IssuedBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='JobAddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='JobName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='POAmount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='SiteContactName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='SitePhoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='UploadDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='UserName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='WCSup',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='WorkOrderDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
