# Generated by Django 4.0.6 on 2022-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0002_alter_workorder_closedate_alter_workorder_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='PO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='prismID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workOrderId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
