# Generated by Django 4.0.6 on 2022-08-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0003_alter_workorder_po_alter_workorder_prismid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='PO',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorder',
            name='POAmount',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorder',
            name='prismID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ), 
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('prismID', 'PO', 'POAmount')},
        ),

    ]
