# Generated by Django 4.0.6 on 2022-08-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0005_workorderduplicate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorderduplicate',
            unique_together={('prismID', 'workOrderId', 'PO', 'POAmount', 'ConstType', 'ConstCoordinator', 'WorkOrderDate', 'EstCompletion', 'IssuedBy', 'JobName', 'JobAddress', 'SiteContactName', 'SitePhoneNumber', 'Comments', 'Status', 'CloseDate', 'WCSup', 'UploadDate', 'UserName')},
        ),
    ]
