# Generated by Django 4.0.6 on 2022-08-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0006_alter_workorderduplicate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='POAmount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workOrderId',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('prismID', 'workOrderId', 'PO')},
        ),
    ]
