# Generated by Django 4.0.6 on 2022-08-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0007_alter_workorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorderduplicate',
            unique_together={('prismID', 'workOrderId', 'PO', 'POAmount', 'WorkOrderDate')},
        ),
    ]
