# Generated by Django 4.0.6 on 2022-08-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0008_alter_workorderduplicate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorderduplicate',
            unique_together={('prismID', 'workOrderId', 'PO', 'POAmount')},
        ),
    ]
