# Generated by Django 4.0.6 on 2022-09-10 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workOrder', '0009_alter_workorderduplicate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('LocationID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=100, null=True)),
                ('termination_date', models.CharField(blank=True, max_length=200, null=True)),
                ('hire_created', models.CharField(blank=True, max_length=200, null=True)),
                ('hourly_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.locations')),
                ('supervisor_name', models.ForeignKey(blank=True, db_column='supervisor_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.employee')),
                ('user', models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.locations'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='WCSup',
            field=models.ForeignKey(blank=True, db_column='WCSup', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.employee'),
        ),
    ]
