# Generated by Django 4.0.6 on 2022-09-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0010_locations_employee_workorder_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
