# Generated by Django 4.0.6 on 2022-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0011_workorder_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='linkedOrder',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
