# Generated by Django 4.0.6 on 2022-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0012_workorder_linkedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
