# Generated by Django 4.0.6 on 2022-10-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0013_employee_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('itemID', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateField()),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_perc', models.CharField(blank=True, max_length=220, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_payout', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='workOrder.item')),
                ('location', models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.CASCADE, to='workOrder.locations')),
            ],
            options={
                'unique_together': {('item', 'location')},
            },
        ),
    ]
