# Generated by Django 4.0.6 on 2022-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0014_item_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='pay_perc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
