# Generated by Django 4.0.6 on 2022-10-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0015_alter_itemprice_pay_perc'),
    ]

    operations = [
        migrations.CreateModel(
            name='payrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('employee', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('prismID', models.CharField(max_length=200)),
                ('workOrderId', models.CharField(max_length=200)),
                ('PO', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
            options={
                'unique_together': {('location', 'employee', 'date', 'prismID', 'workOrderId', 'PO', 'item')},
            },
        ),
        migrations.CreateModel(
            name='payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('employee', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('prismID', models.CharField(max_length=200)),
                ('workOrderId', models.CharField(max_length=200)),
                ('PO', models.CharField(max_length=200)),
                ('RT', models.CharField(blank=True, max_length=200, null=True)),
                ('OT', models.CharField(blank=True, max_length=200, null=True)),
                ('DT', models.CharField(blank=True, max_length=200, null=True)),
                ('IT', models.CharField(blank=True, max_length=200, null=True)),
                ('RTPrice', models.CharField(blank=True, max_length=200, null=True)),
                ('OTPrice', models.CharField(blank=True, max_length=200, null=True)),
                ('bonus', models.CharField(blank=True, max_length=200, null=True)),
                ('production', models.CharField(blank=True, max_length=200, null=True)),
                ('ownVehicle', models.CharField(blank=True, max_length=200, null=True)),
                ('onCall', models.CharField(blank=True, max_length=200, null=True)),
                ('payroll', models.CharField(blank=True, max_length=200, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('itemTotal', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('pdfDaily', models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                'unique_together': {('location', 'employee', 'date', 'prismID', 'workOrderId', 'PO')},
            },
        ),
    ]
