# Generated by Django 4.0.6 on 2022-10-04 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0016_payrolldetail_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='woId',
            field=models.ForeignKey(blank=True, db_column='woId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.workorder'),
        ),
    ]
