# Generated by Django 4.0.6 on 2022-10-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0018_alter_workorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='internalPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('pickupEmployee', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.CharField(blank=True, max_length=600, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('subcontractor', models.BooleanField(default=False)),
                ('woID', models.ForeignKey(db_column='woID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.workorder')),
            ],
            options={
                'unique_together': {('id', 'woID')},
            },
        ),
    ]
