# Generated by Django 4.0.6 on 2022-10-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0019_internalpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pre_invoice',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
