# Generated by Django 4.0.6 on 2022-10-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0020_workorder_invoice_workorder_pre_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='invoice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='pre_invoice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
