# Generated by Django 4.0.6 on 2022-12-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0021_alter_workorder_invoice_alter_workorder_pre_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodID', models.IntegerField()),
                ('periodYear', models.IntegerField()),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('payDate', models.DateField()),
                ('weekRange', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.IntegerField()),
                ('day', models.DateField()),
                ('supervisor', models.CharField(blank=True, max_length=200, null=True)),
                ('own_vehicle', models.FloatField(blank=True, null=True)),
                ('total_pay', models.IntegerField(blank=True, null=True)),
                ('split_paymet', models.BooleanField(default=False)),
                ('Location', models.ForeignKey(db_column='Location', on_delete=django.db.models.deletion.CASCADE, to='workOrder.locations')),
                ('Period', models.ForeignKey(db_column='Period', on_delete=django.db.models.deletion.CASCADE, to='workOrder.period')),
                ('woID', models.ForeignKey(blank=True, db_column='woID', null=True, on_delete=django.db.models.deletion.CASCADE, to='workOrder.workorder')),
            ],
            options={
                'unique_together': {('Period', 'Location', 'day', 'crew')},
            },
        ),
        migrations.CreateModel(
            name='DailyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('DailyID', models.ForeignKey(db_column='DailyID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.daily')),
                ('itemID', models.ForeignKey(db_column='itemID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.itemprice')),
            ],
            options={
                'unique_together': {('DailyID', 'itemID')},
            },
        ),
        migrations.CreateModel(
            name='DailyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_to_pay', models.FloatField(blank=True, null=True)),
                ('on_call', models.FloatField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('start_lunch_time', models.IntegerField(blank=True, null=True)),
                ('end_lunch_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('regular_hours', models.FloatField(blank=True, null=True)),
                ('ot_hour', models.FloatField(blank=True, null=True)),
                ('double_time', models.FloatField(blank=True, null=True)),
                ('payout', models.FloatField(blank=True, null=True)),
                ('DailyID', models.ForeignKey(db_column='DailyID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.daily')),
                ('EmployeeID', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.employee')),
            ],
            options={
                'unique_together': {('DailyID', 'EmployeeID')},
            },
        ),
    ]
