# Generated by Django 4.0.6 on 2022-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0022_period_daily_dailyitem_dailyemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='pdfDaily',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
