# Generated by Django 4.0.6 on 2022-12-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0023_daily_pdfdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='pdfDaily',
            field=models.FileField(null=True, upload_to='dailys'),
        ),
        migrations.CreateModel(
            name='employeeRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recap', models.FileField(null=True, upload_to='Recaps')),
                ('EmployeeID', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.employee')),
                ('Period', models.ForeignKey(db_column='Period', on_delete=django.db.models.deletion.CASCADE, to='workOrder.period')),
            ],
            options={
                'unique_together': {('Period', 'EmployeeID')},
            },
        ),
    ]
