# Generated by Django 4.0.6 on 2022-12-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0024_alter_daily_pdfdaily_employeerecap'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecap',
            name='mailingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
