# Generated by Django 4.0.6 on 2022-12-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0025_employeerecap_mailingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerecap',
            name='mailingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
