# Generated by Django 4.0.6 on 2023-01-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0026_alter_employeerecap_mailingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployee',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyitem',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
