# Generated by Django 4.0.6 on 2023-01-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0027_dailyemployee_created_date_dailyitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemployee',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyitem',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
