# Generated by Django 4.0.6 on 2023-01-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0028_alter_dailyemployee_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='receipt',
            field=models.FileField(null=True, upload_to='dailys'),
        ),
    ]
