# Generated by Django 4.0.6 on 2023-01-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0030_alter_internalpo_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpo',
            name='receipt',
            field=models.ImageField(null=True, upload_to='internal_po'),
        ),
    ]
