# Generated by Django 4.0.6 on 2023-01-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0031_alter_internalpo_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpo',
            name='receipt',
            field=models.ImageField(null=True, upload_to='po'),
        ),
        migrations.CreateModel(
            name='woStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentStatus', models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced')], max_length=20, null=True)),
                ('nextStatus', models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('woID', models.ForeignKey(db_column='woID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.workorder')),
            ],
        ),
    ]
