# Generated by Django 4.0.6 on 2023-01-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0032_alter_internalpo_receipt_wostatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
