# Generated by Django 4.0.6 on 2023-01-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0033_daily_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpo',
            name='pickupEmployee',
            field=models.ForeignKey(blank=True, db_column='pickupEmployee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.employee'),
        ),
    ]
