# Generated by Django 4.0.6 on 2023-01-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0034_alter_internalpo_pickupemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpo',
            name='pickupEmployee',
            field=models.ForeignKey(blank=True, db_column='pickupEmployee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickupEmployee', to='workOrder.employee'),
        ),
        migrations.AlterField(
            model_name='internalpo',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_column='supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='workOrder.employee'),
        ),
    ]
