# Generated by Django 4.0.6 on 2023-01-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0036_period_approvedby_period_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_superAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='createdBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
