# Generated by Django 4.0.6 on 2023-01-21 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0038_subcontractor_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.vendor'),
        ),
    ]
