# Generated by Django 4.0.6 on 2023-01-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0040_alter_internalpo_receipt_externalproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproduction',
            name='invoice',
            field=models.FileField(null=True, upload_to='external_invoice'),
        ),
    ]
