# Generated by Django 4.0.6 on 2023-01-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0041_alter_externalproduction_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalproduction',
            old_name='total',
            new_name='total_invoice',
        ),
        migrations.RemoveField(
            model_name='externalproduction',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='externalproduction',
            name='quantity',
        ),
        migrations.AddField(
            model_name='externalproduction',
            name='subcontractor',
            field=models.ForeignKey(blank=True, db_column='subcontractor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.subcontractor'),
        ),
        migrations.CreateModel(
            name='externalProdItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('externalProdID', models.ForeignKey(db_column='externalProdID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.externalproduction')),
                ('itemID', models.ForeignKey(db_column='itemID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.itemprice')),
            ],
        ),
    ]
