# Generated by Django 4.0.6 on 2023-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0043_externalproduction_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='nonBillable',
            field=models.BooleanField(default=False),
        ),
    ]
