# Generated by Django 4.0.6 on 2023-01-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0048_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimateNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
