# Generated by Django 4.0.6 on 2023-01-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0049_estimate_estimatenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estimate',
            new_name='woEstimate',
        ),
    ]
