# Generated by Django 4.0.6 on 2023-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0050_rename_estimate_woestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced')], default=1),
        ),
        migrations.AddField(
            model_name='internalpo',
            name='estimate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='internalpo',
            name='invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
