# Generated by Django 4.0.6 on 2023-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0052_woinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='woestimate',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
