# Generated by Django 4.0.6 on 2023-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0053_woestimate_is_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='accounts_payable',
            field=models.BooleanField(default=False),
        ),
    ]
