# Generated by Django 4.0.6 on 2023-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0054_employee_accounts_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
