# Generated by Django 4.0.6 on 2023-02-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0055_locations_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalpo',
            name='subcontractor',
        ),
    ]
