# Generated by Django 4.0.6 on 2023-02-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0056_remove_internalpo_subcontractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalpo',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
