# Generated by Django 4.0.6 on 2023-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0057_alter_internalpo_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='woinvoice',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
