# Generated by Django 4.0.6 on 2023-02-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0059_authorizedbilling_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedbilling',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
