# Generated by Django 4.0.6 on 2023-02-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0060_alter_authorizedbilling_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedbilling',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='authorizedbilling',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
