# Generated by Django 4.0.6 on 2023-02-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0061_authorizedbilling_updatedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woestimate',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Updated')], default=1),
        ),
        migrations.AlterField(
            model_name='woinvoice',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Closed'), (3, 'Updated')], default=1),
        ),
        migrations.CreateModel(
            name='employeeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('LocationID', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.locations')),
                ('employeeID', models.ForeignKey(blank=True, db_column='employeeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.employee')),
            ],
            options={
                'unique_together': {('employeeID', 'LocationID')},
            },
        ),
    ]
