# Generated by Django 4.0.6 on 2023-02-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0062_alter_woestimate_status_alter_woinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployee',
            name='dt_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemployee',
            name='emp_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemployee',
            name='ot_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyemployee',
            name='rt_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
