# Generated by Django 4.0.6 on 2023-02-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0063_dailyemployee_dt_pay_dailyemployee_emp_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployee',
            name='production',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
