# Generated by Django 4.0.6 on 2023-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0064_dailyemployee_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
