# Generated by Django 4.0.6 on 2023-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0065_dailyitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitem',
            name='emp_payout',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
