# Generated by Django 4.0.6 on 2023-03-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0066_dailyitem_emp_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='isAmountRounded',
            field=models.BooleanField(default=True),
        ),
    ]
