# Generated by Django 4.0.6 on 2023-03-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0067_internalpo_isamountrounded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='total_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
