# Generated by Django 4.0.6 on 2023-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0069_woinvoice_estimatenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='woestimate',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woestimate',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woestimate',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woestimate',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='woinvoice',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woinvoice',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woinvoice',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woinvoice',
            name='zipCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
