# Generated by Django 4.0.6 on 2023-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0075_authorizedbilling_transferby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedbilling',
            name='transferQty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
