# Generated by Django 4.0.6 on 2023-04-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0076_authorizedbilling_transferqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='poNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
