# Generated by Django 4.0.6 on 2023-04-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0078_alter_authorizedbilling_transferqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='createdBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='internalpo',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
