# Generated by Django 4.0.6 on 2023-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0079_internalpo_createdby_internalpo_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='transferFromPO',
            field=models.ForeignKey(blank=True, db_column='transferFromPO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferFromPO', to='workOrder.workorder'),
        ),
        migrations.AddField(
            model_name='internalpo',
            name='transferToPO',
            field=models.ForeignKey(blank=True, db_column='transferToPO', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferToPO', to='workOrder.workorder'),
        ),
        migrations.AlterField(
            model_name='internalpo',
            name='woID',
            field=models.ForeignKey(db_column='woID', on_delete=django.db.models.deletion.CASCADE, related_name='woID', to='workOrder.workorder'),
        ),
    ]
