# Generated by Django 4.0.6 on 2023-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0080_internalpo_transferfrompo_internalpo_transfertopo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='transferBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='internalpo',
            name='transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
