# Generated by Django 4.0.6 on 2023-05-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0081_internalpo_transferby_internalpo_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyitem',
            name='authorized_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyitem',
            name='autorizedID',
            field=models.ForeignKey(blank=True, db_column='autorizedID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.authorizedbilling'),
        ),
        migrations.AddField(
            model_name='dailyitem',
            name='createdBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dailyitem',
            name='isAuthorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyitem',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dailyitem',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
