# Generated by Django 4.0.6 on 2023-07-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0083_externalproditem_authorized_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationDetail', models.TextField(blank=True, max_length=500, null=True)),
                ('operationType', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('DailyID', models.ForeignKey(db_column='DailyID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.daily')),
            ],
        ),
    ]
