# Generated by Django 4.0.6 on 2023-08-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0084_dailyaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='payrollAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('operationDetail', models.TextField(blank=True, max_length=1000, null=True)),
                ('operationType', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('Location', models.ForeignKey(db_column='Location', on_delete=django.db.models.deletion.CASCADE, to='workOrder.locations')),
                ('Period', models.ForeignKey(db_column='Period', on_delete=django.db.models.deletion.CASCADE, to='workOrder.period')),
            ],
        ),
    ]
