# Generated by Django 4.0.6 on 2023-08-31 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0086_loginaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaudit',
            name='EmployeeID',
            field=models.ForeignKey(blank=True, db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='workOrder.employee'),
        ),
        migrations.AlterField(
            model_name='loginaudit',
            name='Location',
            field=models.ForeignKey(blank=True, db_column='Location', null=True, on_delete=django.db.models.deletion.CASCADE, to='workOrder.locations'),
        ),
        migrations.AlterField(
            model_name='loginaudit',
            name='Period',
            field=models.ForeignKey(blank=True, db_column='Period', null=True, on_delete=django.db.models.deletion.CASCADE, to='workOrder.period'),
        ),
    ]
