# Generated by Django 4.0.6 on 2023-11-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0088_wocommentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployee',
            name='billableHours',
            field=models.BooleanField(default=False),
        ),
    ]
