# Generated by Django 4.0.6 on 2024-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0090_dailyemployee_status_dailyemployee_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authorizedbilling',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced'), (4, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='dailyemployee',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced'), (4, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='dailyitem',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced'), (4, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='externalproditem',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced'), (4, 'Removed')], default=1),
        ),
        migrations.AlterField(
            model_name='internalpo',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced'), (4, 'Removed')], default=1),
        ),
    ]
