# Generated by Django 4.0.6 on 2024-03-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0091_employee_is_manager_alter_authorizedbilling_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='pay70Percent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='payPercent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
