# Generated by Django 4.0.6 on 2024-10-07 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0093_alter_subcontractor_paypercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wostatuslog',
            name='currentStatus',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wostatuslog',
            name='nextStatus',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='woAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimateNumber', models.IntegerField(null=True)),
                ('invoiceNumber', models.IntegerField()),
                ('adjustment', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('woID', models.ForeignKey(db_column='woID', on_delete=django.db.models.deletion.CASCADE, to='workOrder.workorder')),
            ],
        ),
    ]
