# Generated by Django 4.0.6 on 2024-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0094_alter_workorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woadjustment',
            name='invoiceNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
