# Generated by Django 4.0.6 on 2024-10-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0095_alter_woadjustment_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woadjustment',
            name='estimateNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='woadjustment',
            name='invoiceNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
