# Generated by Django 4.0.6 on 2024-10-25 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0096_alter_woadjustment_estimatenumber_and_more'),
        ('timesheet', '0002_timesheet_period_timesheet_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='crew',
            field=models.ForeignKey(blank=True, db_column='crew', null=True, on_delete=django.db.models.deletion.CASCADE, to='workOrder.daily'),
        ),
    ]
